export const QUERIES = {
    SIMILARITY: "jd_resume_similarity",
    LABEL: "label",
    COMPANIES: "companies"
};

export const RESUME_UPLOAD_STATUS = {
    RESUME_WORKFLOW_PROGRESS: "RESUME_WORKFLOW_PROGRESS",
    RESUME_WORKFLOW_FAILED: "RESUME_WORKFLOW_FAILED",
    RESUME_WORKFLOW_COMPLETED: "RESUME_WORKFLOW_COMPLETED",
    RESUME_WORKFLOW_IDLE: "RESUME_WORKFLOW_IDLE"
}

export const JD_UPLOAD_STATUS = {
    JD_WORKFLOW_PROGRESS: "RESUME_WORKFLOW_PROGRESS",
    JD_WORKFLOW_FAILED: "RESUME_WORKFLOW_FAILED",
    JD_WORKFLOW_COMPLETED: "RESUME_WORKFLOW_COMPLETED",
    JD_WORKFLOW_IDLE: "RESUME_WORKFLOW_IDLE"
}