/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "", // Optional, if using Identity Pool
    "aws_cognito_region": "ap-south-1",  // The region for Cognito
    "aws_user_pools_id": "ap-south-1_HId4pQZQS",  // Your Cognito User Pool ID
    "aws_user_pools_web_client_id": "4fc8i1l6icmjqac3f0r3rhej2r",  // Your Cognito App Client ID
    "oauth": {
    }
};


export default awsmobile;
